4.自定义异常

继承Exception、Throwable等

```javascript
public class MyException extends Exception{
	public MyException(){
	}
	
	public MyException(String message){
		super(message);
	}
}
```



```javascript
public class Test {

	//抛出MyException
	public static void func() throws MyException{
		throw new MyException("自定义错误");
	}
	
	public static void main(String[] args) {
		//捕获MyException
		try {
			func();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}
```

